### ISSUE TITLE
Crash after use of "Regenerate Terrain" and pressing F10

### ISSUE THREAD

**Issue by bgn68** [Aidiakapi/controllinator#3]
I had a crash after I regenerated the terrain and then, by accident, pressed F10:

Error while running event controllinator::controllinator-debug-pause (ID 140)
__controllinator__/debug_session.lua:29: cannot start a debug session because entities overlap
stack traceback:
	[C]: in function 'error'
	__controllinator__/debug_session.lua:29: in function 'new'
	__controllinator__/interface.lua:104: in function 'new_debug_session'
	__controllinator__/interface.lua:359: in function 'on_gui_debug_toggle'
	__controllinator__/interface.lua:367: in function 'on_gui_debug_pause'
	__controllinator__/control.lua:206: in function <__controllinator__/control.lua:205>

Maybe the basic reason is not in your mod, but in "Regenerate Terrain". I don't know. At least it should not crash but give an error message in this case and do nothing.

**Comment by Aidiakapi** [comment]
Looking into the issue, this error should never occur, because interface:new_debug_session tests the same condition, and prints a message to the screen when this situation occurs.

It's also shouldn't have anything to do with the other mod. That mod might delete entities (or cause then to be deleted because water spawns under it), but improper deletion (deletion without firing an event) should be handled without issue.

Rather, this situation should only occur in multiplayer. Do you maybe have a save file that I could inspect? If not, I'm planning to rework this mod in a little bit of time, to make use of new 0.17 features, and greatly improved the robustness and usefulness.

**Comment by bgn68** [comment]
You're right, it has nothing to do with "Regenerate Terrain". Today I tried the same game but before regenerating and without the regenerate mod and got another crash just by starting the game and pressing F10:

Error while running event controllinator::controllinator-debug-pause (ID 140)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	__controllinator__/interface.lua:92: in function 'new_debug_session'
	__controllinator__/interface.lua:359: in function 'on_gui_debug_toggle'
	__controllinator__/interface.lua:367: in function 'on_gui_debug_pause'
	__controllinator__/control.lua:206: in function <__controllinator__/control.lua:205>
stack traceback:
	[C]: in function '__index'
	__controllinator__/interface.lua:92: in function 'new_debug_session'
	__controllinator__/interface.lua:359: in function 'on_gui_debug_toggle'
	__controllinator__/interface.lua:367: in function 'on_gui_debug_pause'
	__controllinator__/control.lua:206: in function <__controllinator__/control.lua:205>

Here the link to that save file:
https://nextcloud.bgn-it.de/nextcloud/index.php/s/Szk4faWbZLao7yX

This is a big map and I use a lot of mods. Also I always play in god mode but the crash appears also after disabling god mode. I never played in multiplayer. I tried it with much smaller test maps, also with all mods enabled, but then there was no crash.

I never used controllinator so it is not important to urgently fix this.

**Comment by Aidiakapi** [comment]
Fixed by 7266b8bee41327e6d9df7ce9a06e80c03728f142.
